config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users, except: :index 
  end
  resources :posts do
    resources :answers, except: :index do
      resources :best_answers, only: :create
    end
  end
  root 'posts#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_one :best_answer, dependent: :destroy


  validates :body, presence: true, length: { maximum: 1000 }
  validates_uniqueness_of :post_id, scope: :user_id
  scope :recent, -> { order(updated_at: :desc) }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :recent, -> { order(updated_at: :desc) }

end

app/models/best_answer.rb
class BestAnswer < ApplicationRecord
  belongs_to :answer
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true, length: { maximum: 1000 }
  validates :title, presence: true, length: { maximum: 30 }
  belongs_to :category
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_one :best_answer, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[title body]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :best_answer, dependent: :destroy

  has_secure_password
  
  validates :nick_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :gender, presence: true
  validates :age, presence: true
  validates :occupation, presence: true

  scope :recent, -> { order(updated_at: :desc) }

  def already_bestanswered?(post)
    self.best_answer.exists?(post_id: post.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: '登録が完了しました'
    else
      render :new
    end
  end

  def edit
    if @user.id != current_user.id
      redirect_to root_path, notice: 'その操作はできません'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'ユーザー情報を更新しました'
    else
      render :edit
    end
  end


  def show
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'アカウントを削除しました'
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :email, :password, :password_confirmation, :gender, :age, :occupation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_post, only: [:new, :create, :show, :edit, :update]
  before_action :set_answer, only: [:show, :edit, :update]

  def new
    @answer = Answer.new
    if @post.user_id == current_user.id
      redirect_to root_path, notice: '自分の投稿に回答はできません'
    end
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.attributes = {
      post_id: params[:post_id], 
      user_id: current_user.id
    }
    if @answer.save
      redirect_to @answer.post, notice: '回答しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @answer.user_id != current_user.id
      redirect_to root_path, notice: 'その操作はできません'
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to "/posts/#{@answer.post.id}", notice: '回答を更新しました'
    else
      render :edit
    end
  end

  

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/best_answers_controller.rb
class BestAnswersController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    bestanswer = BestAnswer.new(answer_id: params[:answer_id])
    bestanswer.attributes = {
      post_id: params[:post_id], 
      user_id: current_user.id, 
      answer_id: params[:answer_id]
    }
    bestanswer.save 
      redirect_to post_path(post), notice: 'ベストアンサーを選択しました'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:index]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(10).includes(:user).includes(:best_answer).recent
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.attributes = {
      user: current_user
    }
    if @post.save
      redirect_to @post, notice: '投稿しました'
    else
      render :new
    end
  end

  def show
    @best_answer = BestAnswer.find_by(post_id: params[:id])
    @answer = Answer.where(user_id: current_user.id, post_id: params[:id])
  end

  def edit
    if @post.user_id != current_user.id
      redirect_to root_path, notice: 'その操作はできません'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path notice: '投稿を削除しました'
  end
  
  private
  
  def post_params
    params.require(:post).permit(:body, :title, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/best_answers_helper.rb
module BestAnswersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h1 class="text-center">ユーザー編集</h1>
  <%= form_with model: [:admin, @user], local: true do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class="form-group">
      <%= f.label :nick_name, 'ニックネーム' %>
      <%= f.text_field :nick_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :gender, '性別' %>
      <%= f.select :gender, ["男性", "女性"], {}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :age, '年齢' %>
      <%= f.select :age, [ "20代", "30代", "40代", "50代", "60代", "70代", "80代", "90代" ], {}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :occupation, '職業' %>
      <%= f.select :occupation, [ "会社員", "公務員", "パート・アルバイト", "専業主婦", "無職" ], {}, { class: 'form-control' } %>
    </div>
    <%= f.submit '更新する', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h1 class="text-center">新規登録</h1>
  <%= form_with model: [:admin, @user], local: true do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class="form-group">
      <%= f.label :nick_name, 'ニックネーム' %>
      <%= f.text_field :nick_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :gender, '性別' %>
      <%= f.select :gender, ["男性", "女性"], {}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :age, '年齢' %>
      <%= f.select :age, [ "20代", "30代", "40代", "50代", "60代", "70代", "80代", "90代" ], {}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :occupation, '職業' %>
      <%= f.select :occupation, [ "会社員", "公務員", "パート・アルバイト", "専業主婦", "無職" ], {}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード(確認)' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit '登録する', class: 'btn btn-outline-primary mb-2' %>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <div class="card border-secondary mb-3 p-2">
    <div class="card-header"><h3><b><%= @user.nick_name %></b></h3></div>
    <div class="card-body text-dark">
      <h4 class="card-title border-bottom border-dark"><p><%= @user.gender %></p></h4>
      <h4 class="card-title border-bottom border-dark"><p><%= @user.age %></p></h4>
      <h4 class="card-title border-bottom border-dark"><p><%= @user.occupation %></p></h4>
    </div>
  </div>
  <%= link_to '投稿一覧へ', posts_path, class: 'btn btn-outline-secondary' %>
  <% if @user.id == current_user.id %>
    <%= link_to '編集する', edit_admin_user_path(@user), class: 'btn btn-outline-primary' %>
    <%= button_tag 'このアカウントを削除する', class: 'btn btn-outline-danger', data: { toggle: 'modal', target: '#delete-user' } %>
  <% end %>
  <hr>
  <% if @user.posts.present? %>
    <h2 class="text-center"><%= "#{@user.nick_name}さんの相談事" %></h2>
  <% else %>
    <h2 class="text-center"><%= "#{@user.nick_name}さんの相談事はまだありません" %></h2>
  <% end %>
  <hr>
  <% @user.posts.eager_load(:best_answer).each do |post| %>
    <div class="col-lg-12 col-md-12 col-sm-12 mb-3 mt-3 p-3">
      <div class="card border-secondary bg-light mb-3 p-2">
        <div class="card-header">
          <%= link_to post.title, post_path(post), {:style=>'color: #696969;', :class => "css_class"} %>
        </div>
        <div class="card_body">
          <p><%= truncate(post.body, length: 70) %></p>
          <hr color="#000000">
          <span><%= "#{post.answers.count}件の回答" %></span>
          <% if post.best_answer.present? %>
            <span class="text-danger float-right">解決済み！</span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="modal fade" id="delete-user">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">このアカウントを削除します、よろしいですか？</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">いいえ</button>
        <%= link_to '削除', admin_user_path(@user), method: :delete, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/answers/_answer.html.erb
<%= @post.answers.each do |answer| %>
  <div class="card border-secondary mb-3 p-3">
    <p><b><%= link_to "回答者: #{answer.user.nick_name}さん #{answer.user.gender} #{answer.user.age} #{answer.user.occupation}", 
          admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class"} %>
    <hr>
    <p><%= simple_format answer.body %></p>
    <p>回答日: <%= answer.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
    <% if answer.created_at != answer.updated_at %>
      <p>更新日: <%= answer.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
    <% end %>
    <%= link_to '詳細', "/posts/#{@post.id}/answers/#{answer.id}", class: 'btn btn-outline-primary' %>
    <% unless @post.user.already_bestanswered?(@post) %>
      <% if @post.user_id == current_user.id %>
        <%= link_to "#exampleModal", :data => {:toggle=>"modal", :role => "dialog"}, :class=>"btn btn-outline-danger" do %>
          ベストアンサーにする
        <% end %>
      <% end %>
    <% else %>
        <p>ベストアンサーに選ばれた回答です</p>
    <% end %>
  </div>
<% end %>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">この投稿をベストアンサーにする</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ベストアンサーに選択すると、この相談は解決したことになります、よろしいですか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">いいえ</button>
        <%= link_to "はい！", post_answer_best_answers_path(:answer_id => answer.id, :post_id => @post.id), method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/answers/_form.html.erb
<%= form_with model: [post, answer], local: true do |form| %>
  <%= render "shared/errors", obj: answer %>
  <div class="form-group">
    <%= form.label :body, '回答内容'%>
    <%= form.text_area :body, rows: 10, class: 'form-control' %>
  </div>
  <%= form.submit '回答する', class: 'btn btn-outline-primary' %>
  <%= link_to '戻る', post_path(post), class: 'btn btn-outline-secondary' %>
<% end %>

app/views/answers/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">回答編集</h2>
  <%= form_with model: [@post, @answer], local: true do |form| %>
    <%= render "shared/errors", obj: @answer %>
    <div class="form-group">
      <%= form.label :body, '相談事' %>
      <%= form.text_area :body, rows: 10, class: 'form-control' %>
    </div>
    <%= form.submit '回答を更新する', class: 'btn btn-primary' %>
    <%= link_to '戻る', post_answer_path(@post, @answer), class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/answers/new.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <h2 class="text-center">あなたの回答</h2>
  <div class="mb-3">
  </div>
  <hr>
  <%= render partial: 'form', locals: { post: @post, answer: @answer } %>
</div>

<div class="col-md-10 offset-md-1 mt-5">
  <h2 class="text-center">相談の内容</h2>
  <div class="card border-secondary mb-3 p-2">
    <div class="card-header"><p><b><%= @post.title %></b></p></div>
    <div class="card-body text-dark">
      <h4 class="card-title border-bottom border-dark"><p><%= @post.category&.name %></p></h4>
      <p class="card-text"><p><%= simple_format @post.body %></p></p>
      <p>投稿日: <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <p><b><%= link_to "相談者: #{@post.user.nick_name}さん #{@post.user.gender} #{@post.user.age} #{@post.user.occupation}", 
            admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class float-right"} %>
    </div>
  </div>
</div>

app/views/answers/show.html.erb
<div class="col-md-10 offset-md-1 mt-5 mb-5">
  <div class="card border-secondary mb-3 p-3 mt-3">
    <p><b><%= link_to "回答者: #{@answer.user.nick_name}さん #{@answer.user.gender} #{@answer.user.age} #{@answer.user.occupation}", 
          admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class"} %>
    <hr size="10">
    <p><%= simple_format @answer.body %></p>
    <p>回答日: <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
    <% if @answer.created_at != @answer.updated_at %>
      <p>更新日: <%= @answer.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
    <% end %>
    <% if @answer.user_id == current_user.id %>
      <%= link_to '編集', edit_post_answer_path(@post, @answer), class: 'btn btn-outline-primary' %>
      <%= link_to '戻る', post_path(@post, @answer), class: 'btn btn-outline-secondary' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>a way?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    html {
      position: relative;
      min-height: 100%;
    }

    body {
      margin-bottom: 60px;
    }

    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px;
      background-color: #f5f5f5;
    }

    html {
      position: relative;
      min-height: 100%;
    }

    body {
      margin-bottom: 60px;
    }

    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px;
      background-color: #f5f5f5;
    }
    </style>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <footer class="footer">
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |form| %>
  <%= render 'shared/errors', obj: post %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: t('.include_blank') }, {class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 10, class: 'form-control' %>
  </div>
  <%= form.submit '投稿する', class: 'btn btn-outline-primary' %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">編集</h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 offset-md-1 mt-5 mb-5">
  <div class="card border-secondary mb-3 p-2">
    <div class="card-header"><p><b><%= @post.title %></b></p></div>
    <div class="card-body text-dark">
      <h4 class="card-title border-bottom border-dark"><p><%= @post.category&.name %></p></h4>
      <p class="card-text"><p><%= simple_format @post.body %></p></p>
      <p>投稿日: <%= @post.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% if @post.created_at != @post.updated_at %>
        <p>更新日: <%= @post.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% end %>
      <p><b><%= link_to "相談者: #{@post.user.nick_name}さん #{@post.user.gender} #{@post.user.age} #{@post.user.occupation}", 
            admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class float-right"} %>
    </div>
  </div>
  <% if @post.user_id == current_user.id %>
    <%= link_to '編集', edit_post_path(@post), class: 'btn btn-outline-primary' %>
    <%= button_tag '削除', class: 'btn btn-outline-danger', data: { toggle: 'modal', target: '#delete-post' } %>
  <% elsif @answer.present? %>
    <p>既に回答しました！</p>
  <% else %>
    <div class="pb-1">
      <%= link_to '回答する', new_post_answer_path(@post), class: 'btn btn-outline-info pr-5 pl-5' %>
    </div>
  <% end %>
  <%= link_to '戻る', posts_path, class: 'btn btn-outline-secondary' %>
  <% if @best_answer.present? %>
    <hr>
    <h2 class="text-center">ベストアンサーに選ばれた回答</h2>
    <hr>
    <div class="card border-secondary mb-3 p-3">
      <p><b><%= link_to "回答者: #{@best_answer.answer.user.nick_name}さん #{@best_answer.answer.user.gender} #{@best_answer.answer.user.age} #{@best_answer.answer.user.occupation}", 
            admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class"} %>
      <hr>
      <p><%= simple_format @best_answer.answer.body %></p>
      <p>回答日: <%= @best_answer.answer.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% if @best_answer.answer.created_at != @best_answer.answer.updated_at %>
        <p>更新日: <%= @best_answer.answer.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% end %>
      <%= link_to '詳細', "/posts/#{@post.id}/answers/#{@best_answer.answer.id}", class: 'btn btn-outline-primary' %>
      <p class="pt-3"><b class="text-danger">ベストアンサーに選ばれた回答です！</b></p>
    </div>
  <% end %>
    <hr>
    <% if @post.answers.present?%>
      <h2 class="text-center">回答一覧</h2>
    <% else %>
      <h2 class="text-center">まだ誰も回答していません</h2>
    <% end %>
  <hr>
  <% @post.answers.eager_load(:user).each do |answer| %>
    <div class="card border-secondary mb-3 p-3">
      <p><b><%= link_to "回答者: #{answer.user.nick_name}さん #{answer.user.gender} #{answer.user.age} #{answer.user.occupation}", 
            admin_user_path(@post.user), {:style=>'color: #696969;', :class => "css_class"} %>
      <hr>
      <p><%= simple_format answer.body %></p>
      <p>回答日: <%= answer.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% if answer.created_at != answer.updated_at %>
        <p>更新日: <%= answer.updated_at.strftime("%Y年%m月%d日 %H:%M:%S") %></p>
      <% end %>
      <%= link_to '詳細', "/posts/#{@post.id}/answers/#{answer.id}", class: 'btn btn-outline-primary' %>
      <% unless @post.user.already_bestanswered?(@post) %>
        <% if @post.user_id == current_user.id%>
          <%= link_to "#exampleModal", :data => {:toggle=>"modal", :role => "dialog"}, :class=>"btn btn-outline-danger" do %>
            ベストアンサーにする
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">この投稿をベストアンサーにする</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ベストアンサーに選択すると、この相談は解決したことになります、よろしいですか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">いいえ</button>
        <%= link_to "はい！", post_answer_best_answers_path(answer_id: @post.answers.ids, post_id: @post.id), method: :post, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="delete-post">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">この投稿を削除しますか？</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">いいえ</button>
        <%= link_to '削除', post_path(@post), method: :delete, class: "btn btn-outline-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-light bg-light ">
  <p class="mx-auto">©a way?</p>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/posts">a way？</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="container">
      <div class="row">
        <% if current_user != nil %>
          <p><b><%= link_to "#{current_user&.nick_name}", admin_user_path(current_user), class: 'ml-3 text-dark' %> さんがログイン中</b></p>
        <% end %>
      </div>
    </div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          メニュー
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if current_user != nil %>
              <%= link_to '投稿する', new_post_path, class: 'dropdown-item' %>
              <%= link_to 'マイページ', admin_user_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
            <% else %>
              <%= link_to '新規登録', new_admin_user_path, class: 'dropdown-item' %>
              <%= link_to 'ログイン', login_path, class: 'dropdown-item' %>
            <% end %>
          </div>
      </li>
    </ul>
  </div>
</nav>